// auto-assignment & notification system

import storage from './storage.js';
import { generateId } from './utils.js';
import { loadChartSymbol, ASSETS, CONFLUENCE_OPTIONS } from './trading.js';

// ---- constants ----

const STORAGE_SCHEDULE = 'auto_assign_schedule';
const STORAGE_LAST_CHECK = 'auto_assign_last_check';
const STORAGE_ASSIGNMENTS = 'assignments';

/* {asset}, {timeframe}, {concept} get replaced in these */
const ASSIGNMENT_TEMPLATES = [
  'Identify all {concept} on {asset} ({timeframe}) and mark them on the chart.',
  'Analyse {asset} on {timeframe}. Find areas where {concept} is present and annotate.',
  'Open {asset} ({timeframe}) and mark every {concept} you can find. Screenshot your work.',
  'Do a full market structure breakdown on {asset} ({timeframe}). Focus on {concept}.',
  'Study {asset} on {timeframe}. Identify {concept} and note potential trade setups.',
  'Find 3 examples of {concept} on {asset} ({timeframe}). Draw your zones.',
  'Backtest {concept} on {asset} ({timeframe}) for the last 2 weeks. Note your findings.',
  'Perform a top-down analysis of {asset} starting from HTF down to {timeframe}. Mark {concept}.',
];

const CONCEPTS = [
  'Market Structure (BOS/CHOCH)',
  'Order Blocks',
  'Fair Value Gaps',
  'Liquidity Sweeps',
  'Supply & Demand Zones',
  'Key Support/Resistance Levels',
  'Premium/Discount Zones',
  'Fibonacci Retracements',
  'Candlestick Patterns',
  'Session Timing Analysis',
];

const TIMEFRAMES = ['5M', '15M', '30M', '1H', '4H', 'Daily'];

const ALL_ASSETS_FLAT = Object.values(ASSETS).flat();

// ---

function el(tag, className, text) {
  const node = document.createElement(tag);
  if (className) node.className = className;
  if (text !== undefined) node.textContent = text;
  return node;
}

function randomFrom(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

function getWeekId() {
  // ISO week identifier: "2026-W22"
  const d = new Date();
  const jan1 = new Date(d.getFullYear(), 0, 1);
  const weekNum = Math.ceil(((d - jan1) / 86400000 + jan1.getDay() + 1) / 7);
  return `${d.getFullYear()}-W${String(weekNum).padStart(2, '0')}`;
}

function getTodayStr() {
  const d = new Date();
  return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
}

// schedule engine

// get or create this week's schedule (3 random days)
function getWeekSchedule() {
  const weekId = getWeekId();
  let schedule = storage.get(STORAGE_SCHEDULE, null);

  if (!schedule || schedule.weekId !== weekId) {

    const allDays = [0, 1, 2, 3, 4, 5, 6];
    const picked = [];
    while (picked.length < 3) {
      const idx = Math.floor(Math.random() * allDays.length);
      picked.push(allDays.splice(idx, 1)[0]);
    }
    picked.sort((a, b) => a - b);
    schedule = { weekId, days: picked, firedDates: [] };
    storage.set(STORAGE_SCHEDULE, schedule);
  }

  return schedule;
}

function generateAutoAssignment() {
  const asset = randomFrom(ALL_ASSETS_FLAT);
  const concept = randomFrom(CONCEPTS);
  const timeframe = randomFrom(TIMEFRAMES);
  const template = randomFrom(ASSIGNMENT_TEMPLATES);

  const text = template
    .replace('{asset}', asset)
    .replace('{timeframe}', timeframe)
    .replace('{concept}', concept);

  return {
    id: generateId(),
    text,
    asset,
    concept,
    timeframe,
    completed: false,
    autoGenerated: true,
    createdAt: new Date().toISOString(),
  };
}

// ---- notification popup ----

function showAssignmentPopup(assignment) {
  const overlay = el('div', 'notif-overlay');

  const popup = el('div', 'notif-popup');

  const topBar = el('div', 'notif-topbar');
  popup.appendChild(topBar);

  const header = el('div', 'notif-header');
  header.appendChild(el('span', 'notif-icon', '📝'));
  header.appendChild(el('h3', 'notif-title', 'New Assignment!'));
  popup.appendChild(header);

  popup.appendChild(el('p', 'notif-text', assignment.text));

  const tagRow = el('div', 'notif-tags');
  tagRow.appendChild(el('span', 'tag', assignment.asset));
  tagRow.appendChild(el('span', 'tag', assignment.timeframe));
  tagRow.appendChild(el('span', 'tag', assignment.concept));
  popup.appendChild(tagRow);

  const actions = el('div', 'notif-actions');

  const acceptBtn = el('button', 'btn btn-primary notif-btn', '✅ Accept & Go to Chart');
  acceptBtn.addEventListener('click', () => {

    const all = storage.get(STORAGE_ASSIGNMENTS, []);
    all.push(assignment);
    storage.set(STORAGE_ASSIGNMENTS, all);

    overlay.classList.add('notif-closing');
    setTimeout(() => overlay.remove(), 300);

    loadChartSymbol(assignment.asset);
  });
  actions.appendChild(acceptBtn);

  const dismissBtn = el('button', 'btn btn-ghost notif-btn', '🔔 Later');
  dismissBtn.addEventListener('click', () => {
    overlay.classList.add('notif-closing');
    setTimeout(() => overlay.remove(), 300);
  });
  actions.appendChild(dismissBtn);

  popup.appendChild(actions);
  overlay.appendChild(popup);
  document.body.appendChild(overlay);

  requestAnimationFrame(() => overlay.classList.add('notif-visible'));
}

// ---- main check (app startup) ----

export function checkAutoAssignment() {
  const schedule = getWeekSchedule();
  const today = new Date().getDay(); // 0-6
  const todayStr = getTodayStr();

  if (!schedule.days.includes(today)) return;

  if (schedule.firedDates.includes(todayStr)) return;

  const assignment = generateAutoAssignment();

  // delay so app renders first
  setTimeout(() => {
    showAssignmentPopup(assignment);
  }, 1500);

  schedule.firedDates.push(todayStr);
  storage.set(STORAGE_SCHEDULE, schedule);
}
